apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: test-components
  description: A collection of all wangzhe example components
spec:
  type: github
  targets:
    - https://github.com/sonichappy/bstage/blob/main/artist-lookup.yaml
